[package]
name = "fritz_tr064_upnp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["rlib", "cdylib"]

[features]
default = []

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
serde-xml-rs = "0.6.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = 'abort'
